repos:
  # Websec hook is MANDATORY, DO NOT comment it.
  - repo: https://github.com/melisource/fury_websec-git-hooks
    rev: v2.0.0
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [post-commit]

  - repo: https://github.com/melisource/fury_datasec-git-hooks
    rev: 1.2.2
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [post-commit]
        verbose: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args:
          [
            --branch,
            master,
            --branch,
            develop,
            --pattern,
            feature/integration.*,
          ]
